### PR TITLE
Make Dependabot update actions

### PR DESCRIPTION
**Pull request by szepeviktor**
There are outdated actions.

[_source_](https://github.com/szepeviktor/byte-level-care/blob/master/.github/dependabot.yml)

### CODE REVIEW

**Comment by staabm** [comment]
Thanks 🙏

**Comment by szepeviktor** [comment]
Glad to contribute.

**Comment by szepeviktor** [comment]
There is no "Dependabot" tab https://github.com/staabm/phpstan-dba/network/dependencies
You may have to enable Dependabot in repository Settings.

**Comment by staabm** [comment]
> Dependabot encountered the following error when parsing your .github/dependabot.yml:
The property '#/updates/1/' contains additional properties ["versioning-strategy"] outside of the schema when none are allowed
Please update the config file to conform with Dependabot's specification.

**Pull request merged**
