### PR TITLE
Fix Composer usage in Unit Tests MySQL workflow

### PR DESCRIPTION
**Pull request by szepeviktor**
Just using Composer the right way.

### CODE REVIEW

**Comment by szepeviktor** [comment]
> [!NOTE]  
> I let you build that matrix. It is fun 🎈

**Comment by szepeviktor** [comment]
BTW prefer-dist and prefer-lowest are totally different animals.
Here it is: https://gist.github.com/szepeviktor/200b45f9805dc8bf3f185f0ade216987

**Comment by staabm** [comment]
thanks

**Comment by szepeviktor** [comment]
Glad to contribute.

**Pull request merged**
