### PR TITLE
don't overwrite reflection cache, when analyzing only a single file in phpstorm

### PR DESCRIPTION
**Pull request by staabm**
references https://github.com/staabm/phpstan-dba/issues/443#issuecomment-1292041749

related phpstan discussion https://github.com/phpstan/phpstan/discussions/8259

### CODE REVIEW

**Comment by staabm** [comment]
@noemi-salaun could you please give this change a try. I think it should prevent phpstorm-dba to write/change the result cache, when the phpstan analysis was started from within phpstorn

**Comment by noemi-salaun** [comment]
@staabm It looks good. If I update a query, the new query is added in the cache file but everything else is left untouched in the cache file :+1: 
If I keep modifying the same request, every change add a new query in the cache file. Obsolete queries are keeped in the cache file even when I run phpstan manually. I need to remove the cache and re-run phpstan to get a clean cache without obsolete queries.

**Comment by staabm** [comment]
> Obsolete queries are keeped in the cache file even when I run phpstan manually. I need to remove the cache and re-run phpstan to get a clean cache without obsolete queries.

yeah, thats a known issue, see https://github.com/staabm/phpstan-dba/issues/310
it shouldn't be a problem though, when obsolete queries are contained in the cache file

**Comment by staabm** [comment]
I can no longer reproduce the underlying issue. we need a failing unit test first

**Pull request merged**
