### PR TITLE
Allow simulation of DateTime objects

### PR DESCRIPTION
**Pull request by Seldaek**
Partially addresses #278 - but the way I see it, in QuerySimulation::simulateParamValueType you don't have access to the param types argument, only to the parameter themselves?

I mean `PDO::exec($query, $params, $paramTypes)` <- this param types arg

Without access to that we can serialize the datetime to a Y-m-d H:i:s format, but it won't be always correct, as if you pass Doctrine\DBAL\Types\Types::DATE for ex then it should use Y-m-d only. And strictly speaking we should only simulate/serialize DateTime objects if the appropriate Type is passed in $paramTypes. Otherwise it's unlikely to be a bug if you have a DateTime in there as it will fail at runtime.

This patch does fix the issue I have though so it's a improvement as it allows me to run phpstan-dba on this project of mine, but it's hardly a comprehensive fix.

### CODE REVIEW

**Comment by staabm** [comment]
Could you point me to a code example where this feature is needed?

**Comment by Seldaek** [comment]
There is an example in https://github.com/staabm/phpstan-dba/issues/278 - I don't have anything public sorry. But essentially doctrine allows binding advanced data types, so it'd be great if we could support that here.

**Comment by staabm** [comment]
could you provide a failling unit test?

**Comment by staabm** [comment]
> I mean `PDO::exec($query, $params, $paramTypes)` <- this param types arg

hmm are you sure there is more then 1 arg to `PDO::exec`?

https://www.php.net/manual/en/pdo.exec.php

**Comment by staabm** [comment]
ohh I see, you actually meant `$connection->executeUpdate` and friends

**Comment by staabm** [comment]
@Seldaek just to confirm - this PR as is would unblock you (I am willing to merge it and handle it as a kind of beta-feature)

**Pull request merged**
