### PR TITLE
Datetime support

### PR DESCRIPTION
**Pull request by jakubvojacek**
related to https://github.com/staabm/phpstan-dba/issues/476

### CODE REVIEW

**Comment by staabm** [comment]
I think we should add a `DbalApi` class like

```
final class DbalApi {
  public const API_DIBI = 'dibi';
  public const API_DOCTRINE_DBAL = 'doctrine-dbal';
  //.. 

  /** @param self::API_* $type
  public function __construct($api) {}
  
  public function returnsDateTime():bool {
    return $this->api === self::API_DIBI;
  }
}
```

and pass it to the `QueryReflection` constructor.

in https://github.com/staabm/phpstan-dba/blob/c28ca1759967d3433f31493bdba05c09db332ab4/src/QueryReflection/QueryReflection.php#L373 we can then pass it further into the reflector (I think we might need a new method in the`QueryReflector` interface)

**Comment by jakubvojacek** [comment]
> we can then pass it further into the reflector (I think we might need a new method in theQueryReflector interface)

its an interface, I cannot add method to query reflector. Just the signature and then i'd have to add the method body to all 7 seven reflectors that implement `QueryReflection` and inside the QueryReflection I'd have to pass it to constructor of the Mapper class.

Should I go ahead and do that? Also, do you think the dbapi should be nullable?  so that it would only be set when some special return would be required (now only for dibi)?

```diff
--- a/src/QueryReflection/QueryReflection.php
+++ b/src/QueryReflection/QueryReflection.php
@@ -43,6 +43,16 @@ final class QueryReflection
      */
     private static $runtimeConfiguration;
 
+    /**
+     * @var DbaApi|null
+     */
+    private $dbaApi;
+
+    public function __construct(?DbaApi $dbaApi = null)
+    {
+        $this->dbaApi = $dbaApi;
+    }
+
`

**Comment by staabm** [comment]
> Also, do you think the dbapi should be nullable?

yes, I think so.



> its an interface, I cannot add method to query reflector.

feel free to add a method. I don't expect anyone is implementing it outside of phpstan-dba.

**Comment by jakubvojacek** [comment]
ok, on it

**Pull request closed without merging**
