### PR TITLE
Add ECS and apply standard sets

### PR DESCRIPTION
**Pull request by TomasVotruba**
- replace cs fixer with ecs
- update compose run
- [cs] apply PSR-12 and other sets

### CODE REVIEW

**Comment by TomasVotruba** [comment]
As request yesterday :) 

I see the php-cs-fixer now requires PHP 7.3, which is a pitty. ECS solves this :+1: 

I've applied all typical comon sets, including PSR 12 and strict types. Let me know if there is something you really don't like.O

**Comment by staabm** [comment]
Looks great. 🙏

**Comment by TomasVotruba** [comment]
Awesome :+1:

**Comment by staabm** [comment]
btw: I have also running a [green PHP 7.2 CI job](https://github.com/staabm/phpstan-dba/pull/523).

**Pull request merged**
